
1. ENTRYPOINT: is an executable file which will define what is going to be executed as a part of the container
also, default parameters that cannot be overridden when docker containers run with CLI parameters

2. CMD: sets default parameter that can be overridden from the Command Line Interface when container is running,
there should be a single CMD command within the Dockerfile,
for instances where there are multiple CMD commands in a Dockerfile, all except the last one are ignored for an execution

ex: CMD["executable", "parameter1", "parameter2"]

in kubernetes the ENTRYPOINT and CMD can be overridden with argument and command files

example pod:

apiVersion: v1
kind: pod
metadata:
    name: <pod-name>
    labels:
        purpose: demonstrate-command
spec:
    containers:
    - name: command-demo-container
      image: debian
      command: ["printenv"]                <-- ENTRYPOINT to container
      args: ["HOSTNAME,"KUBERNETES_PORT"]  <-- command line arguments
    restartPolicy: OnFailure


3. to check if the command is okay to be executed
kubectl run nginx-webapp --image=nginx:1.20 --dry-run=client

4. extract the manifest/yaml file for the pod(or any resource) from the cli
kubectl run nginx-webapp --image=nginx:1.20 --port=8080 --dry-run=client -o yaml

